import type { NextPage, InferGetStaticPropsType } from "next";
import Head from "next/head";
import Link from "../components/link";
import { getAllPosts } from "../lib/api";
import Button from "@mui/material/Button";

type Props = InferGetStaticPropsType<typeof getStaticProps>;

export const getStaticProps = async () => {
  const allPosts = getAllPosts();
  return {
    props: { allPosts },
  };
};

const Home: NextPage<Props> = ({ allPosts }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {allPosts.map((post) => (
        <Link href="/posts/[slug]" as={`/posts/${post.slug}`} key={post.title}>
          {post.title}
        </Link>
      ))}
      <Button variant="contained">MUI Test Button</Button>
    </div>
  );
};

export default Home;
